-- stylua: ignore
return {
    chktex = { filetypes = { "tex" } },
    codespell = { filetypes = { "*" } },
    cppcheck = { filetypes = { "cpp", "c" } },
    credo = { filetypes = { "elixir" } },
    cspell = { filetypes = { "markdown" } },
    eslint = { filetypes = { "javascript", "javascriptreact", "typescript", "typescriptreact", "vue" } },
    eslint_d = { filetypes = { "javascript", "javascriptreact", "typescript", "typescriptreact", "vue" } },
    flake8 = { filetypes = { "python" } },
    golangci_lint = { filetypes = { "go" } },
    hadolint = { filetypes = { "dockerfile" } },
    luacheck = { filetypes = { "lua" } },
    markdownlint = { filetypes = { "markdown" } },
    misspell = { filetypes = { "*" } },
    mypy = { filetypes = { "python" } },
    phpcs = { filetypes = { "php" } },
    phpstan = { filetypes = { "php" } },
    proselint = { filetypes = { "markdown", "tex" } },
    psalm = { filetypes = { "php" } },
    pylama = { filetypes = { "python" } },
    pylint = { filetypes = { "python" } },
    qmllint = { filetypes = { "qml" } },
    revive = { filetypes = { "go" } },
    rubocop = { filetypes = { "ruby" } },
    selene = { filetypes = { "lua" } },
    shellcheck = { filetypes = { "sh" } },
    standardrb = { filetypes = { "ruby" } },
    staticcheck = { filetypes = { "go" } },
    statix = { filetypes = { "nix" } },
    stylelint = { filetypes = { "scss", "less", "css", "sass" } },
    teal = { filetypes = { "teal" } },
    vale = { filetypes = { "markdown", "tex" } },
    vint = { filetypes = { "vim" } },
    write_good = { filetypes = { "markdown" } },
    yamllint = { filetypes = { "yaml" } },
}
