local h = require("null-ls.helpers")
local methods = require("null-ls.methods")

return h.make_builtin({
    name = "gpp",
    async = true,
    meta = {
        url = "gcc.gnu.org",
        description = "GCC, the GNU Compier Collection",
    },
    method = methods.internal.DIAGNOSTICS_ON_SAVE,
    filetypes = {  "cpp" },
    to_temp_file = true,
    generator = h.generator_factory({
        command = "g++",
        args = {
            "-std=c17",
            "-Wextra",
            "-Wwrite-strings",
            "-Winit-self",
            "-Wuninitialized",
            "-Wmissing-declarations",
            "-Wanalyzer-too-complex",
            "-Wshadow",
            "-Wdisabled-optimization",
            "-Wdouble-promotion",
            "-Winit-self",
            "-pedantic-errors",
            "-Wformat=2",
            "-Wformat-overflow=2",
            "-Wstrict-overflow=5",
            "-Warray-bounds=2",
            "-Wmissing-prototypes",
            "-Wcast-qual",
            "-Wcast-align=strict",
            "-Wconversion",
            "-Wformat-signedness",
            "-Winline",
            "-Wlogical-op",
            "-Wnested-externs",
            "-Wnull-dereference",
            "-Wstack-protector",
            "-Wstrict-prototypes",
            "-Wunsuffixed-float-constants",
            "-Wsign-conversion",
            "-Wtrampolines",
            "-Wswitch-default",
            "-Wswitch-enum",
            "-Wall",
            "$FILENAME",
            "-o /dev/null",
        },
        to_stdin = false,
        from_stderr = true,
        format = "line",
        on_output = h.diagnostics.from_pattern(
            [[^([^:]+):(%d+):(%d+):%s+([^:]+):%s+(.*)$]],
            { "file", "row", "col", "severity", "message" },
            {
                severities = {
                    ["fatal error"] = h.diagnostics.severities.error,
                    ["error"] = h.diagnostics.severities.error,
                    ["note"] = h.diagnostics.severities.information,
                    ["warning"] = h.diagnostics.severities.warning,
                },
            }
        ),
    }),
})
